name: Deploy to IPFS via Pinata

on:
  push:
    branches:
      - main  

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Pin to Pinata
      uses: anantaramdas/ipfs-pinata-deploy-action@v1.6.4
      with:
        pin-name: 'My personal site'
        path: './picture'
        pinata-api-key: ${{ secrets.PINATA_API_KEY }}
        pinata-secret-api-key: ${{ secrets.PINATA_SECRET_API_KEY }}
        verbose: true
        remove-old: false
